### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by lainnorton** [wanglab-broad/ClusterMap#1]
Hi authors,

I tried to use `pip install git+https://github.com/LiuLab-Bioelectronics-Harvard/ClusterMap.git` to install, but it showed "Command errored out with exit status 128". 

I changed "git+https" to "git+git". This time it could be downloaded successfully, but the site-packages folder only contained "ClusterMap-0.0.1.dist-info", which cannot be imported. 

I finally tried to use `git clone` and used the command `python setup.py install` to install. But it showed "warning: install_lib:'build/lib' does not exist - no Python modules to install".

What should I do to successfully install ClusterMap?

**Comment by yichunher** [comment]
Hi,

Thanks for asking!

Could you try first `git clone https://github.com/wanglab-broad/ClusterMap.git` to download the package locally, then `cd ClusterMap` and `pip install -e.`?

For the environment, I added a .yml file so you can use `conda env create -f environment.yml` to create a good environment named `ClusterMap` with required packages.
Thanks!

**Comment by lainnorton** [comment]
> Hi,
> 
> Thanks for asking!
> 
> Could you try first `git clone https://github.com/wanglab-broad/ClusterMap.git` to download the package locally, then `cd ClusterMap` and `pip install -e.`?
> 
> For the environment, I added a .yml file so you can use `conda env create -f environment.yml` to create a good environment named `ClusterMap` with required packages. Thanks!

Hi @heihaizhengdong 

Thanks for the reply!
Through this way, I successfully installed ClusterMap and imported. 

Thanks!

**Comment by rocketeer1998** [comment]
Hi @heihaizhengdong , I'm installing ClusterMap on my Windows10 computer following your instruction. But I got a long list of `ResolvePackageNotFound` error after typing `conda env create -f environment.yml`. I've tried to solve this problem by moving the problematic dependencies from `dependencies` to `pip`. So the environment is successfully created. However, I still can't import the modules that i need in Clustermap. Any recommendations?

**Comment by ruqianl** [comment]
@rocketeer1998 
Yeah, I had the same error on Linux. After some digging, I found that the provided yml only works for Mac since it specifies the platform-specific build versions. 
See: https://stackoverflow.com/questions/55554431/conda-fails-to-create-environment-from-yml/55576493#55576493

Basically, removing the "=hddfnxxx" should fix it.

**Comment by westalone** [comment]
I am trying to  install ClusterMap on HPC(CentOS) using this trick, but the system still failed to install, a lot of conflicting packages....Any clues to solve it? Thanks a lot!
> Basically, removing the "=hddfnxxx" should fix it.
