### ISSUE TITLE
ClusterMap_STARmap_V1_1020_BY1.ipynb file corrupted

### ISSUE THREAD

**Issue by westalone** [wanglab-broad/ClusterMap#11]
This notebook was not shown in github, and it could not be opened on local computer. Hope the authors can fix/update it. Thanks a lot!

**Comment by yichunher** [comment]
Hi, the ClusterMap_STARmap_V1_1020_BY1.ipynb file is too large to be displayed on GitHub. You can open it on your local computer instead. If you encounter any issues with the local host, you can access it using Google Colab through this link: https://colab.research.google.com/github/wanglab-broad/ClusterMap/blob/main/ClusterMap_STARmap_V1_1020_BY1.ipynb.
