### ISSUE TITLE
Vignette Enhancement

### ISSUE THREAD

**Issue by rocketeer1998** [wanglab-broad/ClusterMap#2]
Hi @heihaizhengdong Thanks for your excellent work! And I'd like to use clustermap to analyze my ISS data. However, I'm totally a beginner in python. So could you provide a more detailed vignette on the module installation, and a test run using test data? Thanks!

**Comment by yichunher** [comment]
Hi,
Thanks for asking!
For installation please refer to the post here: https://github.com/wanglab-broad/ClusterMap/issues/1#issuecomment-999330366
For test run on test data, please refer to two jupyter notebooks [here](https://github.com/wanglab-broad/ClusterMap/blob/fec51cd2ebc19aa3b67123e1ebd759757f6331d0/ClusterMap_STARmap_V1_1020_BY1.ipynb) and [here](https://github.com/wanglab-broad/ClusterMap/blob/fec51cd2ebc19aa3b67123e1ebd759757f6331d0/ClusterMap_STARmap_human_cardiac_organoid.ipynb).

**Comment by rocketeer1998** [comment]
> Hi, Thanks for asking! For installation please refer to the post here: [#1 (comment)](https://github.com/wanglab-broad/ClusterMap/issues/1#issuecomment-999330366) For test run on test data, please refer to two jupyter notebooks [here](https://github.com/wanglab-broad/ClusterMap/blob/fec51cd2ebc19aa3b67123e1ebd759757f6331d0/ClusterMap_STARmap_V1_1020_BY1.ipynb) and [here](https://github.com/wanglab-broad/ClusterMap/blob/fec51cd2ebc19aa3b67123e1ebd759757f6331d0/ClusterMap_STARmap_human_cardiac_organoid.ipynb).

OK. Thank you! I'll give it a try and go back to you later.

**Comment by rocketeer1998** [comment]
Hi @heihaizhengdong , I'm installing ClusterMap on my Windows10 computer following your instruction. But I got a long list of `ResolvePackageNotFound` error after typing `conda env create -f environment.yml`. I've tried to solve this problem by moving the problematic dependencies from `dependencies` to `pip` in `environment.yml` file. So the environment is successfully created. However, I still can't import the modules that i need in Clustermap. Any recommendations?

**Comment by rocketeer1998** [comment]
> Hi @heihaizhengdong , I'm installing ClusterMap on my Windows10 computer following your instruction. But I got a long list of `ResolvePackageNotFound` error after typing `conda env create -f environment.yml`. I've tried to solve this problem by moving the problematic dependencies from `dependencies` to `pip` in `environment.yml` file. So the environment is successfully created. However, I still can't import the modules that i need in Clustermap. Any recommendations?

Solved it for now. And I can import all the modules included in `STARmap_human_cardiac_organoid` vignette correctly. But I didn't create a new environment in the way which is illustrated above because there were so many "packages conflicts".

**Comment by yichunher** [comment]
Hi,

Sorry for the late reply. Glad to see the problem was solved!
