### ISSUE TITLE
Export cell segmentation plot

### ISSUE THREAD

**Issue by rocketeer1998** [wanglab-broad/ClusterMap#4]
Hi @heihaizhengdong , I'd like to know how to export the cell segmentation plot into a local `.tiff` file after stitching.  `plt.savefig()` seems not working because the figure produced by `model.plot_segmentation` is Nonetype.

**Comment by rocketeer1998** [comment]
And I'd also like to know how to change the figure and dot size of the `model.plot_cell_typing()` result since it is too small for me. Thanks a lot!

**Comment by yichunher** [comment]
Hi,

Sorry for the late reply. I used the following two functions to plot and save. Hope they're helpful. Thanks!

`model.plot_segmentation(figsize=(30,15),s=1,plot_with_dapi=False,plot_dapi=True,show=False,
save=True,savepath=figpath_save)`

`model.save_segmentation(path_save)`
