### ISSUE TITLE
Export clustermap object

### ISSUE THREAD

**Issue by rocketeer1998** [wanglab-broad/ClusterMap#7]
Hi @heihaizhengdong, how can I export the clustermap object produced by clustermap pipeline? Can I export it as a pickle file? Any other recommendations?

**Comment by yichunher** [comment]
Hi, thanks for asking!
`self.spots` can be saved by `model.save_segmentation(path_save)` now. The `clustermap` object cannot be exported right now so other information may need to be saved individually.

**Comment by rocketeer1998** [comment]
Thank you! I'm hoping to see the release of a detailed description about `clustermap` object. Thanks for your contribution.
